server:
  port: 8083

spring:
  application:
    name: producto-service

  datasource:
    url: jdbc:mysql://localhost:3306/bd_producto_dev
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

empresa:
  ambiente: desarrollo

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      categoriaService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
